import Head from "next/head";
import react from "react";
import useSupabase from "../../supabase";
import NavigationBar from "/components/NavigationBar";
import ChatWidget from "../../components/ChatWidget";
import Footer from "/components/Footer";
import { useEffect, useState } from "react";
import "../styles/globals.css";
import styles from "../styles/Home.module.css";
import Image from "next/image";

function MyApp({ Component, pageProps }) {
  const { currentUser, session, supabase } = useSupabase();
  const [loggedIn, setLoggedIn] = useState(false);
  useEffect(() => {
    setLoggedIn(!!session);
  }, [session]);
  return (
    <>
      <Head>
        <title>StarBound</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationBar />
      <Component
        currentUser={currentUser}
        session={session}
        supabase={supabase}
        {...pageProps}
      />
      {loggedIn ? (
        <ChatWidget
          currentUser={currentUser}
          session={session}
          supabase={supabase}
        />
      ) : null}
      <Footer />
    </>
  );
}

export default MyApp;
